version: "1.0"
services:
  frontend:
    build: .
    volumes:
      - ./:/code
    working_dir: /code/
    command: bash -c "npm run build && npm run preview"
    expose:
      - 8000
    ports:
      - "0.0.0.0:8000:8000"